export const locations = [
  "Birmingham",
  "Coventry",
  "Wolverhampton",
  "Solihull",
  "Oldbury",
  "Walsall",
  "Dudley",
  "Edgbaston",
  "Great Barr",
  "Hall Green",
  "Handsworth",
  "Northfield",
  "Quinton",
  "Soho",
  "Sutton Coldfield",
  "Bearwood",
  "Rowley Regis",
  "Cradley Heath",
  "Old Hill",
  "Smethwick",
  "Tipton",
  "Tividale",
  "Wednesbury",
  "West Bromwich",
  "Yew Tree",
  "Balsall Common",
  "Bickenhill",
  "Castle Bromwich",
  "Chelmsley Wood",
  "Dorridge",
  "Elmdon",
  "Hampton-in-Arden",
  "Kingshurst",
  "Knowle",
  "Marston Green",
  "Meriden",
  "Monkspath",
  "Hockley Heath",
  "Allesley",
  "Binley",
  "Keresley",
  "Stoke",
  "Tile Hill",
  "Aldridge",
  "Bloxwich",
  "Brownhills",
  "Darlaston",
  "Pelsall",
  "Pheasey",
  "Shelfield",
  "Willenhall",
  "Brierley Hill",
  "Cradley",
  "Halesowen",
  "Kingswinford",
  "Lye",
  "Netherton",
  "Stourbridge",
  "Quarry Bank",
  "Bilston",
  "Blakenhall",
  "Bushbury",
  "Oxley",
  "Wednesfield",
];
