import Head from "next/head";
import { Header } from "../components/Header";
import { HowItWorks } from "../components/HowItWorks";
import { LandingSection } from "../components/LandingSection";
import { Requirements } from "../components/Requirements";
import { Reviews } from "../components/Reviews";
import { FollowUs } from "../components/FollowUs";
import { Contact } from "../components/Contact";
import { Footer } from "../components/Footer";
import { Services } from "../components/Services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=Open+Sans:wght@400;600;700&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <main>
        <LandingSection />
        <Services />
        <HowItWorks />
        <Requirements />
        <Reviews />
        <FollowUs />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
