on:
  push:
    tags:
      - 'v*'
name: Build static website
jobs:
  build:
    name: Build Next.js application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm ci --legacy-peer-deps
      - name: Build static website
        run: npm run build
      - name: Export static files
        run: npm run export 
      - name: Upload static website
        uses: actions/upload-artifact@v3
        with: 
          name: static-site
          path: out/
